Repository SWYP-team-2th/server, pull requests merged in 2025-03, with the labels that each got.

#95 Feature/delete comment
  src/docs/asciidoc/comments.adoc
  src/main/java/com/swyp8team2/comment/application/CommentService.java
  src/main/java/com/swyp8team2/comment/domain/CommentRepository.java
  src/main/java/com/swyp8team2/comment/presentation/CommentController.java
  src/main/java/com/swyp8team2/common/domain/BaseEntity.java
  src/main/java/com/swyp8team2/common/exception/ErrorCode.java
  src/test/java/com/swyp8team2/comment/application/CommentServiceTest.java
  src/test/java/com/swyp8team2/comment/domain/CommentRepositoryTest.java
  src/test/java/com/swyp8team2/comment/presentation/CommentControllerTest.java
Labels: enhancement

#96 Feature/update comment
  src/docs/asciidoc/comments.adoc
  src/main/java/com/swyp8team2/comment/application/CommentService.java
  src/main/java/com/swyp8team2/comment/domain/Comment.java
  src/main/java/com/swyp8team2/comment/presentation/CommentController.java
  src/main/java/com/swyp8team2/comment/presentation/dto/CommentRequest.java
  src/main/java/com/swyp8team2/comment/presentation/dto/UpdateCommentRequest.java
  src/test/java/com/swyp8team2/comment/application/CommentServiceTest.java
  src/test/java/com/swyp8team2/comment/presentation/CommentControllerTest.java
Labels: enhancement

#102 투표 단일/복수, 삭제 기능 추가
  src/docs/asciidoc/votes.adoc
  src/main/java/com/swyp8team2/common/config/SecurityConfig.java
  src/main/java/com/swyp8team2/common/dev/DataInitializer.java
  src/main/java/com/swyp8team2/common/exception/ErrorCode.java
  src/main/java/com/swyp8team2/post/application/PostService.java
  src/main/java/com/swyp8team2/post/domain/Post.java
  src/main/java/com/swyp8team2/post/domain/VoteType.java
  src/main/java/com/swyp8team2/post/presentation/PostController.java
  src/main/java/com/swyp8team2/post/presentation/dto/CreatePostRequest.java
  src/main/java/com/swyp8team2/post/presentation/dto/PostImageResponse.java
  src/main/java/com/swyp8team2/vote/application/VoteService.java
  src/main/java/com/swyp8team2/vote/domain/Vote.java
  src/main/java/com/swyp8team2/vote/domain/VoteRepository.java
  src/main/java/com/swyp8team2/vote/presentation/VoteController.java
  src/test/java/com/swyp8team2/post/application/PostServiceTest.java
  src/test/java/com/swyp8team2/post/domain/PostTest.java
  src/test/java/com/swyp8team2/post/presentation/PostControllerTest.java
  src/test/java/com/swyp8team2/support/fixture/FixtureGenerator.java
  src/test/java/com/swyp8team2/vote/application/VoteServiceTest.java
  src/test/java/com/swyp8team2/vote/presentation/VoteControllerTest.java
Labels: enhancement

#110 fix: JPEG 변환 시 알파 채널 관련 오류 수정
  src/main/java/com/swyp8team2/image/application/R2Storage.java
Labels: bug

#111 docs: 투표 현황 조회, 댓글 조회 문서 수정
  src/docs/asciidoc/posts.adoc
  src/docs/asciidoc/votes.adoc
  src/test/java/com/swyp8team2/comment/presentation/CommentControllerTest.java
Labels: documentation

#105 Feature/select feed
  src/docs/asciidoc/posts.adoc
  src/main/java/com/swyp8team2/comment/domain/CommentRepository.java
  src/main/java/com/swyp8team2/post/application/PostQueryService.java
  src/main/java/com/swyp8team2/post/application/PostService.java
  src/main/java/com/swyp8team2/post/domain/PostRepository.java
  src/main/java/com/swyp8team2/post/presentation/PostController.java
  src/main/java/com/swyp8team2/post/presentation/dto/FeedResponse.java
  src/main/java/com/swyp8team2/vote/domain/VoteRepository.java
  src/test/java/com/swyp8team2/post/application/PostCommandServiceTest.java
  src/test/java/com/swyp8team2/post/application/PostQueryServiceTest.java
  src/test/java/com/swyp8team2/post/domain/PostRepositoryTest.java
  src/test/java/com/swyp8team2/post/presentation/PostControllerTest.java
  src/test/java/com/swyp8team2/support/fixture/FixtureGenerator.java
  src/test/java/com/swyp8team2/vote/application/VoteServiceTest.java
Labels: enhancement

#129 fix: 닉네임 조회 실패 시 고정 닉네임으로 생성
  src/main/java/com/swyp8team2/user/application/NicknameGenerator.java
  src/main/java/com/swyp8team2/user/domain/NicknameAdjectiveRepository.java
  src/test/java/com/swyp8team2/user/application/NicknameGeneratorTest.java
Labels: bug

#130 fix: 닉네임 조회 실패 시 고정 닉네임으로 생성
  src/main/java/com/swyp8team2/user/application/NicknameGenerator.java
  src/main/java/com/swyp8team2/user/domain/NicknameAdjectiveRepository.java
  src/test/java/com/swyp8team2/user/application/NicknameGeneratorTest.java
Labels: bug
