Repository SWYP-team-2th/server, pull requests merged in 2025-02, with the labels that each got.

#21 Docs/rest docs posts
  src/docs/asciidoc/index.adoc
  src/main/java/com/swyp8team2/post/presentation/PostController.java
  src/main/java/com/swyp8team2/post/presentation/dto/VoteRequestDto.java
  src/test/java/com/swyp8team2/post/presentation/PostControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/request-parts.snippet
Labels: documentation

#23 Feature/upload image
  src/docs/asciidoc/index.adoc
Labels: documentation

#34 docs: 개발 API 문서 댓글 조회 깨짐
  src/test/java/com/swyp8team2/comment/presentation/CommentControllerTest.java
Labels: bug, documentation

#40 투표 현황 조회 추가
  src/docs/asciidoc/posts.adoc
  src/main/java/com/swyp8team2/common/presentation/HttpLoggingFilter.java
  src/main/java/com/swyp8team2/post/application/PostService.java
  src/main/java/com/swyp8team2/post/application/RatioCalculator.java
  src/main/java/com/swyp8team2/post/domain/Post.java
  src/main/java/com/swyp8team2/post/presentation/PostController.java
  src/main/java/com/swyp8team2/post/presentation/dto/CreatePostRequest.java
  src/main/java/com/swyp8team2/post/presentation/dto/PostImageRequestDto.java
  src/main/java/com/swyp8team2/post/presentation/dto/PostImageResponse.java
  src/main/java/com/swyp8team2/post/presentation/dto/PostImageVoteStatusResponse.java
  src/main/java/com/swyp8team2/post/presentation/dto/PostResponse.java
  src/test/java/com/swyp8team2/post/application/PostServiceTest.java
  src/test/java/com/swyp8team2/post/application/RatioCalculatorTest.java
  src/test/java/com/swyp8team2/post/presentation/PostControllerTest.java
Labels: enhancement

#50 미구현 API 추가
  src/docs/asciidoc/comments.adoc
  src/docs/asciidoc/posts.adoc
  src/docs/asciidoc/users.adoc
  src/docs/asciidoc/votes.adoc
  src/main/java/com/swyp8team2/comment/presentation/dto/CommentResponse.java
  src/main/java/com/swyp8team2/common/exception/ApplicationControllerAdvice.java
  src/main/java/com/swyp8team2/common/exception/ErrorCode.java
  src/main/java/com/swyp8team2/post/application/PostService.java
  src/main/java/com/swyp8team2/post/domain/Post.java
  src/main/java/com/swyp8team2/post/presentation/PostController.java
  src/main/java/com/swyp8team2/user/application/UserService.java
  src/main/java/com/swyp8team2/user/presentation/UserController.java
  src/main/java/com/swyp8team2/user/presentation/dto/UserInfoResponse.java
  src/main/java/com/swyp8team2/vote/application/VoteService.java
  src/main/java/com/swyp8team2/vote/presentation/VoteController.java
  src/main/java/com/swyp8team2/vote/presentation/dto/ChangeVoteRequest.java
  src/main/java/com/swyp8team2/vote/presentation/dto/VoteRequest.java
  src/test/java/com/swyp8team2/comment/presentation/CommentControllerTest.java
  src/test/java/com/swyp8team2/post/application/PostServiceTest.java
  src/test/java/com/swyp8team2/post/application/RatioCalculatorTest.java
  src/test/java/com/swyp8team2/post/domain/PostTest.java
  src/test/java/com/swyp8team2/post/presentation/PostControllerTest.java
  src/test/java/com/swyp8team2/support/WebUnitTest.java
  src/test/java/com/swyp8team2/user/presentation/UserControllerTest.java
  src/test/java/com/swyp8team2/vote/application/VoteServiceTest.java
  src/test/java/com/swyp8team2/vote/presentation/VoteControllerTest.java
Labels: bug, enhancement
